# Default Configuration File for the ServerWebsite Plugin
# Make sure all custom message text is inside ' '
# Example: - 'Custom Text'
# -----
enable-web-command: true
enable-vote-command: true
enable-shop-command: true
enable-forum-command: true
enable-online-map-command: true
website-url: www.example.com
vote-url: www.example.com/vote
shop-url: www.example.com/shop
forum-url: www.example.com/forum
online-map-url: map.example.com:8123
underline-url: true
debug: false
web-custom-message: false
vote-custom-message: false
shop-custom-message: false
forum-custom-message: false
online-map-custom-message: false
web-message:
- '&6@&1===================================================&6@'
- '&6  Our Website: &nwww.example.com'
- '&6@&1===================================================&6@'
vote-message:
- '&6@&1===================================================&6@'
- '&6  Voting Link: &nwww.example.com/vote'
- '&6@&1===================================================&6@'
shop-message:
- '&6@&1===================================================&6@'
- '&6  Shop URL: &nwww.example.com/shop'
- '&6@&1===================================================&6@'
forum-message:
- '&6@&1===================================================&6@'
- '&6  Forum URL: &nwww.example.com/forum'
- '&6@&1===================================================&6@'
online-map-message:
- '&6@&1===================================================&6@'
- '&6  Online Map URL: &nmap.example.com:8123'
- '&6@&1===================================================&6@'
