name: ServerWebsite
main: me.steve8playz.serverwebsite.ServerWebsite
version: 5.5
description: Provides links for your website, shop, forum and/or voting site from your Minecraft Server
author: Steve8Playz
commands:
   ServerWebsite:
      description: The Default Command for the Plugin ServerWebsite
      usage: /<command> <reload/debug>
      permission: ServerWebsite.admin
      permission-message: You don't have permission to use this command!
      default: false
   website:
      aliases: [web, site]
      description: Shows you the Server's Website
      usage: /<command>
      permission: ServerWebsite.sites.website
      permission-message: You don't have permission to use this command!
      default: true
   vote:
      description: Shows you the Server's Voting Page
      usage: /<command>
      permission: ServerWebsite.sites.vote
      permission-message: You don't have permission to use this command!
      default: true
   shop:
      description: Shows you the Server's Shop
      usage: /<command>
      permission: ServerWebsite.sites.shop
      permission-message: You don't have permission to use this command!
      default: true
   forum:
      description: Shows you the Server's Forum
      usage: /<command>
      permission: ServerWebsite.sites.forum
      permission-message: You don't have permission to use this command!
      default: true
   online-map:
      description: Shows you the Server's Online Map
      usage: /<command>
      permission: ServerWebsite.sites.online-map
      permission-message: You don't have permission to use this command!
      default: true